# Generated by Django 3.1.1 on 2020-09-22 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("traktor_server", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="balance",
            name="daily_duration",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="balance",
            name="weekly_duration",
            field=models.IntegerField(default=0),
        ),
    ]
